### ISSUE TITLE
3.6 Can't Upload ANY Images

### ISSUE THREAD

**Issue by eurobank** [osclass/Osclass#2001]
PHP 7. I use GD since Imagick is not available on php7 yet.

Now, why the error shows Imagick i have no idea.

Uploading stopped working.

PHP Fatal error:  Uncaught Error: Class 'Imagick' not found in /home/oc-includes/osclass/classes/ImageResizer.php:46
Stack trace:
#0 /home/oc-includes/osclass/classes/ImageResizer.php(24): ImageResizer->__construct('/home/d...')
#1 /home/oc-includes/osclass/controller/ajax.php(297): ImageResizer::fromFile('/home/d...')
#2 /home/index.php(117): CWebAjax->doModel()
#3 {main}
  thrown in /home/oc-includes/osclass/classes/ImageResizer.php on line 46

**Comment by eurobank** [comment]
Seems to be an old theme problem.

Closing this.
