### ISSUE TITLE
getting XHR returned response code 500 when uploading images on item post page 

### ISSUE THREAD

**Issue by abdulghanysyed** [osclass/Osclass#2040]
when i am uploading pics on http://classibook.com/item/new i am facing issue please find the image below

and debug errors are 

#0 /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php(24): ImageResizer->__construct('/home/classibo/...')
#1 /home/classibo/public_html/oc-includes/osclass/controller/ajax.php(297): ImageResizer::fromFile('/home/classibo/...')
#2 /home/classibo/public_html/index.php(117): CWebAjax->doModel()
#3 {main}
thrown in /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php on line 41

please help me...
![screenshot_4](https://cloud.githubusercontent.com/assets/15182895/16392095/c323f1e0-3cc7-11e6-8fcb-d3eb711bbb31.png)

**Comment by conejoninja** [comment]
Please paste here the full error, looks like the first line is missing

**Comment by abdulghanysyed** [comment]
[27-Jun-2016 11:47:13 Asia/Kolkata] PHP Notice:  Undefined index: sPattern in /home/classibo/public_html/oc-content/themes/zara/functions.php on line 807
[27-Jun-2016 11:47:16 Asia/Kolkata] PHP Notice:  Undefined property: Mobile_Detect::$isIphone in /home/classibo/public_html/oc-content/themes/zara/Mobile_Detect.php on line 77
[27-Jun-2016 11:47:16 Asia/Kolkata] PHP Notice:  Undefined index: fk_i_region_id in /home/classibo/public_html/oc-includes/osclass/frm/Item.form.class.php on line 542
[27-Jun-2016 11:47:21 Asia/Kolkata] PHP Notice:  Undefined index: sPattern in /home/classibo/public_html/oc-content/themes/zara/functions.php on line 807
[27-Jun-2016 11:47:26 Asia/Kolkata] PHP Notice:  Undefined index: sPattern in /home/classibo/public_html/oc-content/themes/zara/functions.php on line 807
[27-Jun-2016 11:47:33 Asia/Kolkata] PHP Notice:  Undefined index: sPattern in /home/classibo/public_html/oc-content/themes/zara/functions.php on line 807
[27-Jun-2016 11:47:38 Asia/Kolkata] PHP Fatal error:  Uncaught exception 'Exception' with message '/home/classibo/public_html/oc-content/uploads/temp/qqfile_5770c5021c655.jpg does not exist!' in /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php:41
Stack trace:
#0 /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php(24): ImageResizer->__construct('/home/classibo/...')
#1 /home/classibo/public_html/oc-includes/osclass/controller/ajax.php(297): ImageResizer::fromFile('/home/classibo/...')
#2 /home/classibo/public_html/index.php(117): CWebAjax->doModel()
#3 {main}
  thrown in /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php on line 41

**Comment by conejoninja** [comment]
[27-Jun-2016 11:47:38 Asia/Kolkata] PHP Fatal error: Uncaught exception 'Exception' with message '/home/classibo/public_html/oc-content/uploads/temp/qqfile_5770c5021c655.jpg does not exist!' in /home/classibo/public_html/oc-includes/osclass/classes/ImageResizer.php:41


The file does not exists, please check that the folder has the correct permissions (is writable)

**Comment by abdulghanysyed** [comment]
![image](https://cloud.githubusercontent.com/assets/15182895/16392350/16c9d8a4-3cc9-11e6-8611-e6f7f32b46c9.png)

before it was 755 and i changed to 777 still same issue i am getting, i changed permissions for temp file

**Comment by abdulghanysyed** [comment]
what is the exact permissions i need for those file?

**Comment by abdulghanysyed** [comment]
found the solution creating new temp folder solved the issue,,.. and my question was old temp folder have some pics is this useful? else can i delete that old temp folder?

**Comment by hospedagemdesites** [comment]
Delete old temp folder don´t work for me...
